import type { Metadata } from 'next';
import { StreamVideoProvider } from '@/providers/stream-client';

export const metadata: Metadata = {
  title: 'Boom',
  description: 'Generated by create next app',
  icons: {
    icon: '/icons/logo.svg',
  },
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <StreamVideoProvider>
      <main>{children}</main>
    </StreamVideoProvider>
  );
};

export default RootLayout;
